feat(txts): Add `serializeOptions` For Legacy Transactions
helius-labs/helius-sdk pull request #117
Opened 2024-08-08 17:37 UTC by 0xIchigo

This PR aims to modify the serialization process in `createSmartTransactions`. This is done so users can specify whether they would like to require all signatures or signature verification, giving them greater control over the smart transaction creation process

2024-08-14 17:16 UTC, chukwumaokere requested changes
Code looks good to me, small typo here on the JSDoc

2024-08-14 17:16 UTC, chukwumaokere commented on src/RpcClient.ts
> +   * @param {SerializeConfig} serializeOptions - Options for transaction serialization. This applies only to legacy transactions. Defaults to `{ requireALlSignatures = true, verifySignatures: true }`
```suggestion
   * @param {SerializeConfig} serializeOptions - Options for transaction serialization. This applies only to legacy transactions. Defaults to `{ requireAllSignatures = true, verifySignatures: true }`
```
Just a small typo here

2024-08-14 18:40 UTC, 0xIchigo commented on src/RpcClient.ts
> +   * @param {SerializeConfig} serializeOptions - Options for transaction serialization. This applies only to legacy transactions. Defaults to `{ requireALlSignatures = true, verifySignatures: true }`
Nice find, ty!

2024-08-15 17:57 UTC, DmitriDmitriDmitri approved these changes

2024-08-15 18:08 UTC, merged